---
title: "Ovarian_Regional"
author: "Kiran Sundaram"
date: "11/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE} 
# load necessary libraries
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(caret)
library(cluster)
library(pROC)
library(randomForest)
library(tree)
library(caret)
library(gbm)
library(PresenceAbsence)
library(glmnet)
```

```{r}
# open data frame
data <-  read.csv(file="ovary_data_chemo.csv", header=TRUE, sep=",")
# change survival months to integer
data$Survival.months <- as.integer(data$Survival.months)
colnames(data)[which(names(data) == "Age.recode.with..1.year.olds")] <- "Agegroup"
colnames(data)[which(names(data) == "Race.recode..W..B..AI..API.")] <- "Race"
colnames(data)[which(names(data) == "Histology.recode...broad.groupings")] <- "Histology.Groups"
colnames(data)[which(names(data) == "Chemotherapy.recode..yes..no.unk.")] <- "Chemotherapy"
colnames(data)[which(names(data) == "Vital.status.recode..study.cutoff.used.")] <- "Vital.Status"
# change Race to character to add Hispanic labels - anyone who is labeled "white" or "unknown" for race and "hispanic" in origin recode column will be switched to "hispanic" in race column
data$Race <- as.character(data$Race)
data <- within(data, Race[Race == 'White' & Origin.recode.NHIA..Hispanic..Non.Hisp. == 'Spanish-Hispanic-Latino'] <- 'Spanish-Hispanic-Latino')
data <- within(data, Race[Race == 'Unknown' & Origin.recode.NHIA..Hispanic..Non.Hisp. == 'Spanish-Hispanic-Latino'] <- 'Spanish-Hispanic-Latino')
data$Race <- as.factor(data$Race)
# remove unwanted columns
data <- dplyr::select(data, -Patient.ID,
                      -SEER.registry,
                      -In.research.data,
                      -Origin.recode.NHIA..Hispanic..Non.Hisp.,
                      -Site.recode.ICD.O.3.WHO.2008,
                      -Behavior.recode.for.analysis,
                      -ICCC.site.recode.ICD.O.3.WHO.2008,
                      -Histologic.Type.ICD.O.3, 
                      -Behavior.code.ICD.O.3,
                      -ICD.O.3.Hist.behav..malignant,
                      -Summary.stage.2000..1998..,
                      -RX.Summ..Surg.Prim.Site..1998..,
                      -RX.Summ..Scope.Reg.LN.Sur..2003..,
                      -RX.Summ..Surg.Oth.Reg.Dis..2003..,
                      -Reason.no.cancer.directed.surgery,
                      -Scope.of.reg.lymph.nd.surg..1998.2002.,
                      -RX.Summ..Reg.LN.Examined..1998.2002.,
                      -Surgery.of.oth.reg.dis.sites..1998.2002.,
                      -Site.specific.surgery..1973.1997.varying.detail.by.year.and.site.,
                      -Radiation.to.Brain.or.CNS..1988.1997., 
                      -CS.tumor.size..2004..,
                      -COD.to.site.recode,
                      -SEER.cause.specific.death.classification,
                      -SEER.other.cause.of.death.classification,
                      -Survival.months.flag,
                      -COD.to.site.rec.KM,
                      -Type.of.follow.up.expected,
                      -Behavior.code.ICD.O.2,
                      -Histology.ICD.O.2, 
                      -Recode.ICD.O.2.to.9, 
                      -Recode.ICD.O.2.to.10,
                      -Month.of.diagnosis.recode,
                      -ICD.O.3.Hist.behav)
# add 5 year survival variable column to set - yes or no
data$Five.Year.Survival <- ifelse(data$Survival.months >= 60, 'Yes', 
                                ifelse(data$Survival.months < 60, 'No', NA))
# change to factor
data$Five.Year.Survival <- as.factor(data$Five.Year.Survival)
# change to character
data$State.county <- as.character(data$State.county)
# omit NA
data <- na.omit(data)
as.tibble(data) 
```

```{r}
# edit county variable
data$State.county <- substr(data$State.county,1,nchar(data$State.county)-15)
as.tibble(data)
```

```{r}
# open alaska data frame
alaska <-  read.csv(file="alaska.csv", header=TRUE, sep=",")
colnames(alaska)[which(names(alaska) == "total_est_pct3")] <- "poverty_percent"
colnames(alaska)[which(names(alaska) == "county2")] <- "State.county"
alaska$State.county <- paste("AK: ", alaska$State.county)
as.tibble(alaska)
```

```{r}
# open california data frame
cali <-  read.csv(file="cali.csv", header=TRUE, sep=",")
colnames(cali)[which(names(cali) == "total_est_pct3")] <- "poverty_percent"
colnames(cali)[which(names(cali) == "county2")] <- "State.county"
cali$State.county <- paste("CA: ", cali$State.county)
as.tibble(cali)
```

```{r}
# open connecticut data frame
connecticut <-  read.csv(file="connecticut.csv", header=TRUE, sep=",")
colnames(connecticut)[which(names(connecticut) == "total_est_pct3")] <- "poverty_percent"
colnames(connecticut)[which(names(connecticut) == "county2")] <- "State.county"
connecticut$State.county <- paste("CT: ", connecticut$State.county)
as.tibble(connecticut)
```

```{r}
# open georgia data frame
georgia <-  read.csv(file="georgia.csv", header=TRUE, sep=",")
colnames(georgia)[which(names(georgia) == "total_est_pct3")] <- "poverty_percent"
colnames(georgia)[which(names(georgia) == "county2")] <- "State.county"
georgia$State.county <- paste("GA: ", georgia$State.county)
as.tibble(georgia)
```

```{r}
# open hawaii data frame
hawaii <-  read.csv(file="hawaii.csv", header=TRUE, sep=",")
colnames(hawaii)[which(names(hawaii) == "total_est_pct3")] <- "poverty_percent"
colnames(hawaii)[which(names(hawaii) == "county2")] <- "State.county"
hawaii$State.county <- paste("HI: ", hawaii$State.county)
as.tibble(hawaii)
```

```{r}
# open iowa data frame
iowa <-  read.csv(file="iowa.csv", header=TRUE, sep=",")
colnames(iowa)[which(names(iowa) == "total_est_pct3")] <- "poverty_percent"
colnames(iowa)[which(names(iowa) == "county2")] <- "State.county"
iowa$State.county <- paste("IA: ", iowa$State.county)
as.tibble(iowa)
```

```{r}
# open kentucky data frame
kentucky <-  read.csv(file="kentucky.csv", header=TRUE, sep=",")
colnames(kentucky)[which(names(kentucky) == "total_est_pct3")] <- "poverty_percent"
colnames(kentucky)[which(names(kentucky) == "county2")] <- "State.county"
kentucky$State.county <- paste("KY: ", kentucky$State.county)
as.tibble(kentucky)
```

```{r}
# open louisiana data frame
louis <-  read.csv(file="louis.csv", header=TRUE, sep=",")
colnames(louis)[which(names(louis) == "total_est_pct3")] <- "poverty_percent"
colnames(louis)[which(names(louis) == "county2")] <- "State.county"
louis$State.county <- paste("LA: ", louis$State.county)
as.tibble(louis)
```

```{r}
# open michigan data frame
michigan <-  read.csv(file="mich.csv", header=TRUE, sep=",")
colnames(michigan)[which(names(michigan) == "total_est_pct3")] <- "poverty_percent"
colnames(michigan)[which(names(michigan) == "county2")] <- "State.county"
michigan$State.county <- paste("MI: ", michigan$State.county)
as.tibble(michigan)
```

```{r}
# open new jersey data frame
nj <-  read.csv(file="nj.csv", header=TRUE, sep=",")
colnames(nj)[which(names(nj) == "total_est_pct3")] <- "poverty_percent"
colnames(nj)[which(names(nj) == "county2")] <- "State.county"
nj$State.county <- paste("NJ: ", nj$State.county)
as.tibble(nj)
```

```{r}
# open new mexico data frame
nm <-  read.csv(file="nj.csv", header=TRUE, sep=",")
colnames(nm)[which(names(nm) == "total_est_pct3")] <- "poverty_percent"
colnames(nm)[which(names(nm) == "county2")] <- "State.county"
nm$State.county <- paste("NM: ", nm$State.county)
as.tibble(nm)
```

```{r}
# open utah data frame
utah <-  read.csv(file="utah.csv", header=TRUE, sep=",")
colnames(utah)[which(names(utah) == "total_est_pct3")] <- "poverty_percent"
colnames(utah)[which(names(utah) == "county2")] <- "State.county"
utah$State.county <- paste("UT: ", utah$State.county)
as.tibble(utah)
```

```{r}
# open washington data frame
wash <-  read.csv(file="wash.csv", header=TRUE, sep=",")
colnames(wash)[which(names(wash) == "total_est_pct3")] <- "poverty_percent"
colnames(wash)[which(names(wash) == "county2")] <- "State.county"
wash$State.county <- paste("WA: ", wash$State.county)
as.tibble(wash)
```

```{r}
# join alaska poverty percent based on county
# alaska1 <- merge(data, alaska, by ="State.county")
# as.tibble(alaska1)
```

```{r}
# join cali poverty percent based on county
cali <- merge(cali, data, by ="State.county")
as.tibble(cali)
```

```{r}
# join connecticut poverty percent based on county
connecticut <- merge(data, connecticut, by ="State.county")
as.tibble(connecticut)
```

```{r}
# join georgia poverty percent based on county
georgia <- merge(data, georgia, by ="State.county")
as.tibble(georgia)
```

```{r}
# join hawaii poverty percent based on county
hawaii <- merge(data, hawaii, by ="State.county")
as.tibble(hawaii)
```

```{r}
# join iowa poverty percent based on county
iowa <- merge(data, iowa, by ="State.county")
as.tibble(iowa)
```

```{r}
# join kentucky poverty percent based on county
kentucky <- merge(data, kentucky, by ="State.county")
as.tibble(kentucky)
```

```{r}
# join louisianna poverty percent based on county
louis <- merge(data, louis, by ="State.county")
as.tibble(louis)
```

```{r}
# join michigan poverty percent based on county
michigan <- merge(data, michigan, by ="State.county")
as.tibble(michigan)
```

```{r}
# join new jersey poverty percent based on county
nj <- merge(data, nj, by ="State.county")
as.tibble(nj)
```

```{r}
# join new mexico poverty percent based on county
nm <- merge(data, nm, by ="State.county")
as.tibble(nm)
```

```{r}
# join utah poverty percent based on county
utah <- merge(data, utah, by ="State.county")
as.tibble(utah)
```

```{r}
# join washington poverty percent based on county
wash <- merge(data, wash, by ="State.county")
as.tibble(wash)
```

```{r}
rbind(alaska, cali, connecticut, georgia, hawaii, iowa, kentucky, louis, michigan, nj, nm, utah, wash)
```



```{r}
data$Histology.Groups <- as.character(data$Histology.Groups)
data$Histology.Groups <- ifelse(data$Histology.Groups == '8010-8049: epithelial neoplasms, NOS' | data$Histology.Groups == '8050-8089: squamous cell neoplasms' | data$Histology.Groups == '8140-8389: adenomas and adenocarcinomas' | data$Histology.Groups == '8440-8499: cystic, mucinous and serous neoplasms', data$Histology.Groups, NA)
as.tibble(data$Histology.Groups)
# Histology.Groups[Histology.Groups == '8010-8049: epithelial neoplasms, NOS' | Histology.Groups == '8050-8089: squamous cell neoplasms' | Histology.Groups == '8140-8389: adenomas and adenocarcinomas' | Histology.Groups == '8440-8499: cystic, mucinous and serous neoplasms'] <- 'NA')
data$Histology.Groups <- as.factor(data$Histology.Groups)
as.tibble(data$Histology.Groups)
data %>%
  count(Histology.Groups)
```

```{r}
# omit NA rows (should get rid of 16,269 rows becuase we dont want most of the histology groups)
data <- na.omit(data)
as.tibble(data) 
```

###### Logistic Regression on Ovary Data
```{r}
# get rid of survival months column (it is essentially the same as our classifier)
data <- dplyr::select(data, -Survival.months)
# split into training and testing
train_size <- floor(0.75 * nrow(data))
set.seed(12345)
train_pos <- sample(seq_len(nrow(data)), size = train_size)
train_classification <- data[train_pos, ]
test_classification <- data[-train_pos, ]
ctrl <- trainControl(method = "repeatedcv", repeats = 15,classProbs = T, savePredictions = T)
dim(train_classification)
dim(test_classification)
```

```{r}
# only look at two classes 
train_classifier_log <- train_classification[c(which(train_classification$Five.Year.Survival == "Yes"), which(train_classification$Five.Year.Survival == "No")),]
test_classifier_log <- test_classification[c(which(test_classification$Five.Year.Survival == "Yes"), which(test_classification$Five.Year.Survival == "No")),]
train_classifier_log$status <- factor(train_classifier_log$Five.Year.Survival)
test_classifier_log$status <- factor(test_classifier_log$Five.Year.Survival)
ctrl <- trainControl(method = "repeatedcv", repeats = 15,classProbs = T, savePredictions = T)
# create model
# predict class based on other variables
# pull all columns to predict class
logistic_regression <- train(Five.Year.Survival ~ ., data = train_classifier_log, method = "glm", family= "binomial", trControl = ctrl)
```

```{r}
# summarize logistic regression
logistic_regression
summary(logistic_regression)
```

```{r}
# visualize on ROC Curve
plot(x = roc(predictor = logistic_regression$pred$Yes, response = logistic_regression$pred$obs)$specificities, y = roc(predictor = logistic_regression$pred$Yes, response = logistic_regression$pred$obs)$sensitivities, col= "blue", xlim = c(1, 0), type ="l", main = "Predicting Survivability in Ovarian Cancer Patients Using Linear Regression", ylab = "Sensitivity", xlab = "Specificity")

# AUC is 0.9962
legend("bottomright", legend = paste("Survivor Curve", roc(predictor = logistic_regression$pred$Yes, response = logistic_regression$pred$obs)$auc, sep = ""), col = c("blue"), fill = c("blue"))
```

```{r}
# test independent set
lr_pred <- predict(logistic_regression, newdata=test_classification)

# confusion matrix
cm_lr <- table(pred = lr_pred, true = test_classification$Five.Year.Survival)
cm_lr
```

```{r}
# pcc results
pcc(cm_lr, st.dev=TRUE)
```

###### Lasso Model on Ovary Data
```{r}
# convert training data to matrix format
x <- model.matrix(Five.Year.Survival ~., train_classification)

# convert status to numerical variable
y <- ifelse(train_classification$Five.Year.Survival=="Yes",1,0)

# perform grid search to find optimal value of lambda
cv.out <- cv.glmnet(x, y, alpha = 1, family="binomial", type.measure = "mse" )

# plot result
plot(cv.out)
# min value of lambda
lambda_min <- cv.out$lambda.min
# best value of lambda
lambda_1se <- cv.out$lambda.1se
# regression coefficients
coef(cv.out,s=lambda_1se)
```

```{r}
# get test data
x_test <- model.matrix(Five.Year.Survival ~., test_classification)

# predict class, type=”class”
lasso_prob <- predict(cv.out, newx = x_test, s=lambda_1se, type="response")
lasso_prob
# translate probabilities to predictions
lasso_predict <- rep("No", nrow(test_classification))
lasso_predict[lasso_prob>.5] <- "Yes"

```

```{r}
# confusion matrix
cm_lasso <- table(pred=lasso_predict, true=test_classification$Five.Year.Survival)
cm_lasso
```

```{r}
# pcc results
pcc(cm_lasso, st.dev=TRUE)
```

###### Naive Bayes on Ovary Data
```{r }
# train model on naive bayes
ctrl_nb <- trainControl(method = "repeatedcv", repeats = 15,classProbs = T, savePredictions = T)
naive_bayes <- train(Five.Year.Survival ~ ., data = train_classification, method = "naive_bayes", trControl = ctrl)
```

```{r}
# summarize naive bayes
naive_bayes
summary(naive_bayes)
```

```{r}
# visualize ROC curve
plot(x = roc(predictor = naive_bayes$pred$Yes, response = naive_bayes$pred$obs)$specificities, y = roc(predictor = naive_bayes$pred$Yes, response = naive_bayes$pred$obs)$sensitivities, col= "blue", xlim = c(1, 0), type ="l", main = "Predicting Survivability in Ovarian Cancer Patients Using Naive Bayes", ylab = "Sensitivity", xlab = "Specificity")

# AUC is 0.99
legend("bottomright", legend = paste("Survivor Curve", roc(predictor = naive_bayes$pred$Yes, response = naive_bayes$pred$obs)$auc, sep = ""), col = c("blue"), fill = c("blue"))
```

```{r}
# test independent set
naive_bayes_pred <- predict(naive_bayes, newdata=test_classification)
# confusion matrix
cm_nb <- table(pred = naive_bayes_pred, true = test_classification$Five.Year.Survival)
cm_nb
```

```{r}
# pcc results
pcc(cm_nb, st.dev=TRUE)
```
